# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "./terraform.tfstate"
    resource_group_name  = "acme_rg"
    storage_account_name = "acmetfstatedame"
    subscription_id      = "e91cad16-aa0f-4cf4-ac49-ce7c7e3ed16e"
    tenant_id            = "a84fb88f-90b4-4467-a19a-4a3abd11369f"
  }
}
